# Generated by Django 3.2.6 on 2021-08-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.ImageField(upload_to='pics')),
                ('price', models.TextField()),
                ('flag', models.BooleanField(default=False)),
            ],
        ),
    ]
