# Generated by Django 3.2.6 on 2021-08-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swati', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='img',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
