# Generated by Django 3.2.6 on 2021-08-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swati', '0003_auto_20210806_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='img',
        ),
    ]
